wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699711586.162389
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 1
      - 13
      - 23
      4: 3.10.12
      5: 0.15.7
      8:
      - 5
